name: huluxia_signin
# 新增写入权限，修复git push 403报错
permissions:
  contents: write
on:
  schedule:    # UTC18点 = 北京时间凌晨2点签到
    - cron: '0 23 * * *'
  workflow_dispatch:  # 支持手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: '初始化python环境'
        uses: actions/setup-python@v4
        with:
           python-version: 3.10.11
      - name: '安装依赖'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: '开始运行'
        id: signin-outputs
        env:
          NOTIFIER_TYPE: ${{ secrets.NOTIFIER_TYPE }} 
          # 取消邮箱注释，启用邮件推送
          EMAIL_CONFIG: ${{ secrets.EMAIL_CONFIG }}
          # 不用企业微信，注释掉
          # WECHAT_ROBOT_URL: ${{ secrets.WECHAT_ROBOT_URL }}
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
        run: |
          python ./main.py
